# Generated by Django 6.0.3 on 2026-04-05 16:55

import django.db.models.deletion
import vehicules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicules', '0008_vehicule_crit_air'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemiseEnEtat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ree', models.CharField(blank=True, choices=[('ct', 'Contrôle technique'), ('pieces', 'Pièces'), ('mo', "Main d'oeuvre")], max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[vehicules.models.validateur_prix])),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remises_en_etat', to='vehicules.vehicule')),
            ],
        ),
    ]
