# Generated by Django 6.0.3 on 2026-04-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remise_en_etat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remiseenetat',
            name='type_ree',
            field=models.CharField(blank=True, choices=[('ct', 'Contrôle technique'), ('pieces', 'Pièces'), ('mo', "Main d'oeuvre")], max_length=100, null=True, verbose_name='Type entretien'),
        ),
    ]
