# Generated by Django 6.0.3 on 2026-03-22 14:44

import vehicules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateField()),
                ('vendeur', models.CharField(max_length=100)),
                ('facture_achat', models.FileField(upload_to='factures_achat/', validators=[vehicules.models.validateur_extensions])),
                ('prix_vehicule', models.DecimalField(decimal_places=2, max_digits=10, validators=[vehicules.models.validateur_prix])),
                ('prix_enchere', models.DecimalField(decimal_places=2, max_digits=10, validators=[vehicules.models.validateur_prix])),
                ('prix_transport', models.DecimalField(decimal_places=2, max_digits=10, validators=[vehicules.models.validateur_prix])),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('couleur', models.CharField(max_length=100)),
                ('annee_vehicule', models.IntegerField(validators=[vehicules.models.validateur_annee])),
                ('transmission', models.CharField(max_length=100)),
                ('energie', models.CharField(max_length=100)),
                ('chevaux_dine', models.IntegerField()),
                ('chevaux_fiscaux', models.IntegerField()),
                ('date_vente', models.DateField()),
                ('numero_vente', models.IntegerField()),
                ('facture_vente', models.FileField(upload_to='factures_vente/', validators=[vehicules.models.validateur_extensions])),
                ('acheteur', models.CharField(max_length=100)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, validators=[vehicules.models.validateur_prix])),
            ],
        ),
    ]
