# Generated by Django 6.0.3 on 2026-03-27 19:01

import django.db.models.deletion
import vehicules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateField()),
                ('vendeur', models.CharField(max_length=100)),
                ('facture_achat', models.FileField(upload_to='factures_achat/', validators=[vehicules.models.validateur_extensions])),
                ('prix_vehicule', models.DecimalField(decimal_places=2, max_digits=10, validators=[vehicules.models.validateur_prix])),
                ('prix_enchere', models.DecimalField(decimal_places=2, max_digits=10, validators=[vehicules.models.validateur_prix])),
                ('prix_transport', models.DecimalField(decimal_places=2, max_digits=10, validators=[vehicules.models.validateur_prix])),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('couleur', models.CharField(max_length=100)),
                ('annee_vehicule', models.PositiveIntegerField(validators=[vehicules.models.validateur_annee])),
                ('transmission', models.CharField(max_length=100)),
                ('energie', models.CharField(max_length=100)),
                ('chevaux_dine', models.IntegerField()),
                ('chevaux_fiscaux', models.IntegerField()),
                ('date_vente', models.DateField(blank=True, null=True)),
                ('numero_vente', models.IntegerField(blank=True, null=True)),
                ('facture_vente', models.FileField(blank=True, null=True, upload_to='factures_vente/', validators=[vehicules.models.validateur_extensions])),
                ('acheteur', models.CharField(blank=True, max_length=100, null=True)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[vehicules.models.validateur_prix])),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garages.garage')),
            ],
        ),
    ]
