# Generated by Django 6.0.3 on 2026-03-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='energie',
            field=models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Electrique'), ('hybride', 'Hybride')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='transmission',
            field=models.CharField(choices=[('manuel', 'Manuel'), ('automatique', 'Automatique')], max_length=100),
        ),
    ]
