# Generated by Django 6.0.3 on 2026-03-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0002_alter_vehicule_energie_alter_vehicule_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='kilometrage_achat',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
