# Generated by Django 6.0.3 on 2026-04-03 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0003_vehicule_kilometrage_achat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.marque'),
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.marque')),
            ],
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='modele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.modele'),
        ),
    ]
