# Generated by Django 6.0.3 on 2026-04-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0004_marque_alter_vehicule_marque_modele_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marque',
            old_name='nom',
            new_name='marque',
        ),
        migrations.RenameField(
            model_name='modele',
            old_name='nom',
            new_name='modele',
        ),
    ]
