# Generated by Django 6.0.3 on 2026-04-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0005_rename_nom_marque_marque_rename_nom_modele_modele'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='kilometrabe_vente',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
