# Generated by Django 6.0.3 on 2026-04-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0006_vehicule_kilometrabe_vente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='kilometrabe_vente',
            new_name='kilometrage_vente',
        ),
    ]
