# Generated by Django 6.0.3 on 2026-04-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0007_rename_kilometrabe_vente_vehicule_kilometrage_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='crit_air',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
