# Generated by Django 6.0.3 on 2026-04-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0008_vehicule_crit_air'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
