# Generated by Django 6.0.3 on 2026-08-13 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0005_remove_garage_proprietaire_garage_membres'),
        ('vehicules', '0009_vehicule_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='crit_air',
            field=models.IntegerField(choices=[(0, 'Electrique'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, 'Non classé')]),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='garages.garage'),
        ),
    ]
