# Generated by Django 6.0.3 on 2026-09-05 11:11

import vehicules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0010_alter_vehicule_crit_air_alter_vehicule_garage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='facture_achat',
            field=models.FileField(blank=True, upload_to='factures_achat/', validators=[vehicules.models.validateur_extensions]),
        ),
    ]
