# Generated by Django 6.0.3 on 2026-09-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0011_alter_vehicule_facture_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='immatriculation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
