# Generated by Django 6.0.3 on 2026-03-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('entreprise', 'Entreprise')], default='free', max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duree', models.IntegerField(choices=[(30, 'Mensuel'), (365, 'Annuel')], default=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
