"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
from django.core.exceptions import ImproperlyConfigured

# Le pilote MySQL est adapté dans config/__init__.py, exécuté avant ce
# fichier : inutile de le refaire ici.


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# reading .env file
env = environ.Env(
    DJANGO_DEBUG=(bool, False),
    DJANGO_ALLOWED_HOSTS=(list, []),
)
environ.Env.read_env(env_file=str(BASE_DIR / '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DJANGO_DEBUG')

ALLOWED_HOSTS = env('DJANGO_ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'users',
    'vehicules',
    'garages',
    'abonnements',
    'remise_en_etat',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'users.middleware.HtmxLoginRedirectMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# En développement, django.contrib.staticfiles sert déjà les fichiers :
# WhiteNoise n'est ajouté qu'en production.
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'config.urls'


# Adresse de l'administration : modifiable par variable d'environnement
# pour ne pas exposer /admin/ en production.
URL_ADMINISTRATION = env("DJANGO_URL_ADMINISTRATION", default="admin/")


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Template directory
        'APP_DIRS': True, # Templates in app directory
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'garages.context_processors.garage_actif',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Une variable par information, plutôt qu'une URL unique : c'est plus lisible
# dans un .env, et surtout le mot de passe n'a aucun caractère à encoder.
#
# Développement : rien à écrire, sqlite par défaut.
# Production    : USE_MYSQL=True et les variables DB_*.
#
# En production, sqlite est refusé. Sans ce garde-fou, une variable oubliée
# ferait basculer le site sur une base créée au passage, vide et invisible,
# pendant que la vraie resterait inutilisée.

if env.bool('USE_MYSQL', default=False):
    DATABASES = {
        'default': {
            'ENGINE': env('DB_ENGINE', default='django.db.backends.mysql'),
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST', default='localhost'),
            'PORT': env('DB_PORT', default='3306'),
            'OPTIONS': {
                # utf8mb4 pour que les accents traversent la base sans
                # dommage. Le mode strict refuse d'enregistrer une valeur
                # tronquée au lieu de le faire en silence : sur des montants,
                # c'est indispensable.
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
elif DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    raise ImproperlyConfigured(
        "Base de données non configurée. En production, renseignez USE_MYSQL=True "
        "ainsi que DB_NAME, DB_USER et DB_PASSWORD dans le fichier .env."
    )

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Sur l'hébergement, les dossiers collectés vivent parfois hors du projet :
# les chemins restent pilotables par variable d'environnement.
STATIC_ROOT = env.path('DJANGO_STATIC_ROOT', default=BASE_DIR / 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = env.path('DJANGO_MEDIA_ROOT', default=BASE_DIR / 'media')

# Le stockage à manifeste de WhiteNoise impose un collectstatic préalable :
# on le réserve à la production.
STOCKAGE_STATIQUES = (
    'django.contrib.staticfiles.storage.StaticFilesStorage'
    if DEBUG
    else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
)

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': STOCKAGE_STATIQUES,
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Authentification
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = 'vehicules:garages'

# Session : expiration sur inactivité, pas sur fermeture du navigateur.
#
# Par défaut Django pose un cookie persistant de deux semaines, d'où une
# session qui survit à la fermeture de Chrome, garage actif compris.
#
# SESSION_EXPIRE_AT_BROWSER_CLOSE n'est volontairement pas utilisé : les
# navigateurs réglés sur « reprendre là où vous vous étiez arrêté »
# restaurent les cookies de session, le réglage serait donc sans effet sur
# une bonne partie des postes. Une durée, elle, expire toujours.
#
# SESSION_SAVE_EVERY_REQUEST fait repartir ce délai à chaque page vue : on
# est déconnecté après huit heures sans rien faire, jamais en pleine saisie.
SESSION_COOKIE_AGE = env.int('DJANGO_SESSION_COOKIE_AGE', default=8 * 60 * 60)
SESSION_SAVE_EVERY_REQUEST = True

# CSRF
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True

CSRF_TRUSTED_ORIGINS = env.list('DJANGO_CSRF_TRUSTED_ORIGINS', default=[])


# Sécurité en production
# Ces réglages ne s'appliquent qu'une fois DEBUG à False, pour ne pas
# forcer le HTTPS sur le serveur de développement.

if not DEBUG:
    SECURE_SSL_REDIRECT = env.bool('DJANGO_SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = env.int('DJANGO_SECURE_HSTS_SECONDS', default=3600)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
