# Generated by Django 6.0.3 on 2026-03-27 19:01

import django.db.models.deletion
import garages.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=5, validators=[garages.models.validateur_code_postal])),
                ('telephone', models.CharField(max_length=10, validators=[garages.models.validateur_telephone])),
                ('email', models.EmailField(max_length=254)),
                ('abonnement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonnements.abonnement')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
