# Generated by Django 6.0.3 on 2026-04-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='date_debut_essai',
            field=models.DateField(blank=True, null=True),
        ),
    ]
