# Generated by Django 6.0.3 on 2026-08-13 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0002_garage_date_debut_essai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('gestionnaire', 'Gestionnaire'), ('lecture', 'Lecture')], default='gestionnaire', max_length=20)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='garages.garage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'garage')},
            },
        ),
    ]
