# Generated by Django 6.0.3 on 2026-08-13 11:14

from django.db import migrations


def migrer_proprietaires_vers_membres(apps, schema_editor):
    Garage = apps.get_model('garages', 'Garage')
    GarageMembre = apps.get_model('garages', 'GarageMembre')
    for garage in Garage.objects.exclude(proprietaire__isnull=True):
        GarageMembre.objects.get_or_create(
            user=garage.proprietaire,
            garage=garage,
            defaults={'role': 'gestionnaire'},
        )


def revenir_aux_proprietaires(apps, schema_editor):
    Garage = apps.get_model('garages', 'Garage')
    GarageMembre = apps.get_model('garages', 'GarageMembre')
    for garage in Garage.objects.exclude(proprietaire__isnull=True):
        GarageMembre.objects.filter(garage=garage, user=garage.proprietaire, role='gestionnaire').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0003_garagemembre'),
    ]

    operations = [
        migrations.RunPython(migrer_proprietaires_vers_membres, revenir_aux_proprietaires),
    ]
