# Generated by Django 6.0.3 on 2026-08-13 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0004_migrer_proprietaires_vers_membres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='proprietaire',
        ),
        migrations.AddField(
            model_name='garage',
            name='membres',
            field=models.ManyToManyField(related_name='garages', through='garages.GarageMembre', to=settings.AUTH_USER_MODEL),
        ),
    ]
