# Generated by Django 6.0.3 on 2026-08-14 12:01

import django.core.validators
import django.db.models.deletion
import garages.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0005_remove_garage_proprietaire_garage_membres'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrageComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_ventes_totales', models.CharField(default='707000000', help_text='Compte débité du montant TTC de la marge.', max_length=20, validators=[garages.models.validateur_compte], verbose_name='Ventes totale')),
                ('compte_ventes_prix_achat', models.CharField(default='707010000', help_text='Compte crédité du montant HT de la marge.', max_length=20, validators=[garages.models.validateur_compte], verbose_name="Ventes au prix d'achat HT")),
                ('compte_tva_collectee', models.CharField(default='445710090', help_text='Compte crédité de la TVA calculée sur la marge.', max_length=20, validators=[garages.models.validateur_compte], verbose_name='TVA collectée')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Taux de TVA (%)')),
                ('garage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametrage_comptable', to='garages.garage')),
            ],
            options={
                'verbose_name': 'paramétrage comptable',
                'verbose_name_plural': 'paramétrages comptables',
            },
        ),
    ]
